import React from 'react';
import {View, Text} from 'react-native';
import Table from '../../components/table/Table';

const BannerManagementPage = () => {
  return (
    <View style={{flex: 1}}>
      <Table dataTable={myTableName} isDragNSort />
    </View>
  );
};

export default BannerManagementPage;
const myTableName = [
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
  {
    dataCell: [
      {
        cellType: 'TableCellCheckBox',
        config: {
          width: 170,
          superType: 'BYTE',
          label: '3.53 MB',
          backgroundColor: 'lightblue',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Lorem',
          backgroundColor: 'lightgreen',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Ipsum',
          backgroundColor: 'pink',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Dolor',
          backgroundColor: 'tomato',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
      {
        cellType: 'TableCellText',
        config: {
          width: 170,
          superType: 'BYTE',
          label: 'Sit amet',
          backgroundColor: 'yellow',
          fontColor: false,
          isTouchable: false,
        },
        item: {},
        subItem: {},
      },
    ],
  },
];
