const reduxString = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_SIGNIN: 'AUTH_SIGNIN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SET_FALSE_AFTER_LOGIN: 'SET_FALSE_AFTER_LOGIN',
  UPDATE_CUSTOMER_CONSENT: 'UPDATE_CUSTOMER_CONSENT',
  UPDATE_CUSTOMER_CONSENT_FAIL: 'UPDATE_CUSTOMER_CONSENT_FAIL',

  GET_TITLE_VERSION: 'GET_TITLE_VERSION',
  GET_TITLE_VERSION_FAILED: 'GET_TITLE_VERSION_FAILED',
  GET_ENTERPRISE_LOGO: 'GET_ENTERPRISE_LOGO',
  GET_ENTERPRISE_LOGO_FAILED: 'GET_ENTERPRISE_FAILED',
  GET_ENTERPRISE_LOGO_SUCCESS: 'GET_ENTERPRISE_SUCCESS',
  REMOVE_ENTERPRISE_LOGO: 'REMOVE_ENTERPRISE_LOGO',

  REQUEST_DASHBOARD_DATA: 'REQUEST_DASHBOARD_DATA',
  SET_DASHBOARD_SUMMARY: 'SET_DASHBOARD_SUMMARY',
  REQUEST_ERROR: 'REQUEST_ERROR',
  SET_WIDGET_LIST: 'SET_WIDGET_LIST',
  SET_CAROUSEL: 'SET_CAROUSEL',
  SET_SIM_STATISTICS: 'SET_SIM_STATISTICS',
  SET_TOP_TRAFFIC_STATISTICS: 'SET_TOP_TRAFFIC_STATISTICS',
  REQUEST_WIDGET_DATA: 'REQUEST_WIDGET_DATA',

  UPDATE_DATA_SEARCH_TEXT: 'UPDATE_DATA_SEARCH_TEXT',
  RESET_DATA_SEARCH_TEXT: 'RESET_DATA_SEARCH_TEXT',
  UPDATE_GENERATED_PARAMS: 'UPDATE_GENERATED_PARAMS',
  RESET_GENERATED_PARAMS: 'RESET_GENERATED_PARAMS',
  UPDATE_DATA_FILTER: 'UPDATE_DATA_FILTER',
  RESET_DATA_FILTER: 'RESET_DATA_FILTER',
  SET_LOADING_FILTER_TRUE: 'SET_LOADING_FILTER_TRUE',
  SET_LOADING_FILTER_FALSE: 'SET_LOADING_FILTER_FALSE',
  SET_ERROR_FILTER: 'SET_ERROR_FILTER',
  REMOVE_ALL_HARD_CODE_TRUE: 'REMOVE_ALL_HARD_CODE_TRUE',
  MERGE_DATA_FILTER: 'MERGE_DATA_FILTER',
  MERGE_SPECIFIC_DATA_FILTER_INDEX: 'MERGE_SPECIFIC_DATA_FILTER_INDEX',
  UPDATE_SORT_BY: 'UPDATE_SORT_BY',
  RESET_SORT_BY: 'RESET_SORT_BY',

  GENERATE_QUERY_PARAMS_FILTER_RUN: 'GENERATE_QUERY_PARAMS_FILTER_RUN',
  GENERATE_QUERY_PARAMS_FILTER: 'GENERATE_QUERY_PARAMS_FILTER',
  RESET_QUERY_PARAMS_FILTER: 'RESET_QUERY_PARAMS_FILTER',

  GET_ENTERPRISE_CORP_LOADING: 'GET_ENTERPRISE_CORP_LOADING',
  GET_ENTERPRISE_CORP_FAILED: 'GET_ENTERPRISE_CORP_FAILED',
  GET_ENTERPRISE_CORP_SUCCESS: 'GET_ENTERPRISE_SUCCESS',
  GET_ENTERPRISE_CORP_RESET: 'GET_ENTERPRISE_CORP_RESET',

  GET_ENTERPRISE_PACKAGE_NAME_LOADING: 'GET_ENTERPRISE_PACKAGE_NAME_LOADING',
  GET_ENTERPRISE_PACKAGE_NAME_FAILED: 'GET_ENTERPRISE_PACKAGE_NAME_FAILED',
  GET_ENTERPRISE_PACKAGE_NAME_SUCCESS: 'GET_ENTERPRISE_PACKAGE_NAME_SUCCESS',
  GET_ENTERPRISE_PACKAGE_NAME_RESET: 'GET_ENTERPRISE_PACKAGE_NAME_RESET',

  GET_STATE_LOADING: 'GET_STATE_LOADING',
  GET_STATE_FAILED: 'GET_STATE_FAILED',
  GET_STATE_SUCCESS: 'GET_STATE_SUCCESS',
  GET_STATE_RESET: 'GET_STATE_RESET',

  GET_STATE_LOCK_LOADING: 'GET_STATE_LOCK_LOADING',
  GET_STATE_LOCK_FAILED: 'GET_STATE_LOCK_FAILED',
  GET_STATE_LOCK_SUCCESS: 'GET_STATE_LOCK_SUCCESS',
  GET_STATE_LOCK_RESET: 'GET_STATE_LOCK_RESET',

  GET_CUSTOM_LABEL_LOADING: 'GET_CUSTOM_LABEL_LOADING',

  GET_SIM_INVENTORY_LOADING: 'GET_SIM_INVENTORY_LOADING',
  GET_SIM_INVENTORY_LOADING_FALSE: 'GET_SIM_INVENTORY_LOADING_FALSE',
  GET_SIM_INVENTORY_FAILED: 'GET_SIM_INVENTORY_FAILED',
  GET_SIM_INVENTORY_SUCCESS: 'GET_SIM_INVENTORY_SUCCESS',
  GET_SIM_INVENTORY_RESET: 'GET_SIM_INVENTORY_RESET',
  GET_SIM_INVENTORY_REMOVE_ERROR: 'GET_SIM_INVENTORY_REMOVE_ERROR',
  SET_SIM_INVENTORY_TABLE: 'SET_SIM_INVENTORY_TABLE',
  RESET_SIM_INVENTORY_TABLE: 'RESET_SIM_INVENTORY_TABLE',
  CHANGE_CHECK_SIM_INVENTORY: 'CHANGE_CHECK_SIM_INVENTORY',
  CHANGE_CHECK_SIM_INVENTORY_ALL_TRUE: 'CHANGE_CHECK_SIM_INVENTORY_ALL_TRUE',
  CHANGE_CHECK_SIM_INVENTORY_ALL_FALSE: 'CHANGE_CHECK_SIM_INVENTORY_ALL_FALSE',

  USER_ADMINISTRATION_DYNAMIC_ONCHANGE_TEXT_INPUT:
    'USER_ADMINISTRATION_DYNAMIC_ONCHANGE_TEXT_INPUT',
  USER_ADMINISTRATION_CHANGE_CHECK_HEADER:
    'USER_ADMINISTRATION_CHANGE_CHECK_HEADER',
  USER_ADMINISTRATION_DYNAMIC_ONCHANGE_DROP_DOWN:
    'USER_ADMINISTRATION_DYNAMIC_ONCHANGE_DROP_DOWN',
  USER_ADMINISTRATION_DYNAMIC_SUCCESS: 'USER_ADMINISTRATION_DYNAMIC_SUCCESS',
  USER_ADMINISTRATION_DYNAMIC_FAILED: 'USER_ADMINISTRATION_DYNAMIC_FAILED',
  USER_ADMINISTRATION_DYNAMIC_LOADING: 'USER_ADMINISTRATION_DYNAMIC_LOADING',
  USER_ADMINISTRATION_DYNAMIC_RESET: 'USER_ADMINISTRATION_DYNAMIC_RESET',
  USER_ADMINISTRATION_RESET_ALL_VALUE: 'USER_ADMINISTRATION_RESET_ALL_VALUE',
  USER_ADMINISTRATION_UPDATE_BUNDLE_ARRAY:
    'USER_ADMINISTRATION_UPDATE_BUNDLE_ARRAY',
  USER_ADMINISTRATION_SET_SEARCH_TEXT: 'USER_ADMINISTRATION_SET_SEARCH_TEXT',
  USER_ADMINISTRATION_RESET_SEARCH_TEXT:
    'USER_ADMINISTRATION_RESET_SEARCH_TEXT',
  USER_ADMINISTRATION_GENERATE_PARAMS: 'USER_ADMINISTRATION_SET_PARAMS',
  USER_ADMINISTRATION_RESET_PARAMS: 'USER_ADMINISTRATION_RESET_PARAMS',
  USER_ADMINISTRATION_GET_USER_LOADING: 'USER_ADMINISTRATION_GET_USER_LOADING',
  USER_ADMINISTRATION_GET_USER_SUCCESS: 'USER_ADMINISTRATION_GET_USER_SUCCESS',
  USER_ADMINISTRATION_GET_USER_FAILED: 'USER_ADMINISTRATION_GET_USER_FAILED',
  USER_ADMINISTRATION_GET_USER_RESET: 'USER_ADMINISTRATION_GET_USER_RESET',
  USER_ADMINISTRATION_SET_DATA_USER_GENERATED:
    'USER_ADMINISTRATION_SET_DATA_USER_GENERATED',
  USER_ADMINISTRATION_RESET_DATA_USER_GENERATED:
    'USER_ADMINISTRATION_RESET_DATA_USER_GENERATED',
  USER_ADMINISTRATION_DYNAMIC_CHECK_DATA_USER:
    'USER_ADMINISTRATION_DYNAMIC_CHECK_DATA_USER',
  USER_ADMINISTRATION_DYNAMIC_UNCHECK_DATA_USER:
    'USER_ADMINISTRATION_DYNAMIC_UNCHECK_DATA_USER',
  USER_ADMINISTRATION_CHECK_ALL_DATA_USER:
    'USER_ADMINISTRATION_CHECK_ALL_DATA_USER',
  USER_ADMINISTRATION_UNCHECK_ALL_DATA_USER:
    'USER_ADMINISTRATION_UNCHECK_ALL_DATA_USER',
  USER_ADMINISTRATION_SET_APPLIED_HEADER_SORT:
    'USER_ADMINISTRATION_SET_APPLIED_HEADER_SORT',
  USER_ADMINISTRATION_RESET_APPLIED_HEADER_SORT:
    'USER_ADMINISTRATION_RESET_APPLIED_HEADER_SORT',

  ROLE_ADMINISTRATION_DYNAMIC_ONCHANGE_TEXT_INPUT:
    'ROLE_ADMINISTRATION_DYNAMIC_ONCHANGE_TEXT_INPUT',
  ROLE_ADMINISTRATION_CHANGE_CHECK_HEADER:
    'ROLE_ADMINISTRATION_CHANGE_CHECK_HEADER',
  ROLE_ADMINISTRATION_DYNAMIC_ONCHANGE_DROP_DOWN:
    'ROLE_ADMINISTRATION_DYNAMIC_ONCHANGE_DROP_DOWN',
  ROLE_ADMINISTRATION_DYNAMIC_SUCCESS: 'ROLE_ADMINISTRATION_DYNAMIC_SUCCESS',
  ROLE_ADMINISTRATION_DYNAMIC_FAILED: 'ROLE_ADMINISTRATION_DYNAMIC_FAILED',
  ROLE_ADMINISTRATION_DYNAMIC_LOADING: 'ROLE_ADMINISTRATION_DYNAMIC_LOADING',
  ROLE_ADMINISTRATION_DYNAMIC_RESET: 'ROLE_ADMINISTRATION_DYNAMIC_RESET',
  ROLE_ADMINISTRATION_RESET_ALL_VALUE: 'ROLE_ADMINISTRATION_RESET_ALL_VALUE',
  ROLE_ADMINISTRATION_UPDATE_BUNDLE_ARRAY:
    'ROLE_ADMINISTRATION_UPDATE_BUNDLE_ARRAY',
  ROLE_ADMINISTRATION_SET_SEARCH_TEXT: 'ROLE_ADMINISTRATION_SET_SEARCH_TEXT',
  ROLE_ADMINISTRATION_RESET_SEARCH_TEXT:
    'ROLE_ADMINISTRATION_RESET_SEARCH_TEXT',
  ROLE_ADMINISTRATION_GENERATE_PARAMS: 'ROLE_ADMINISTRATION_SET_PARAMS',
  ROLE_ADMINISTRATION_RESET_PARAMS: 'ROLE_ADMINISTRATION_RESET_PARAMS',
  ROLE_ADMINISTRATION_GET_ROLE_LOADING: 'ROLE_ADMINISTRATION_GET_ROLE_LOADING',
  ROLE_ADMINISTRATION_GET_ROLE_SUCCESS: 'ROLE_ADMINISTRATION_GET_ROLE_SUCCESS',
  ROLE_ADMINISTRATION_GET_ROLE_FAILED: 'ROLE_ADMINISTRATION_GET_ROLE_FAILED',
  ROLE_ADMINISTRATION_GET_ROLE_RESET: 'ROLE_ADMINISTRATION_GET_ROLE_RESET',
  ROLE_ADMINISTRATION_SET_DATA_ROLE_GENERATED:
    'ROLE_ADMINISTRATION_SET_DATA_ROLE_GENERATED',
  ROLE_ADMINISTRATION_RESET_DATA_ROLE_GENERATED:
    'ROLE_ADMINISTRATION_RESET_DATA_ROLE_GENERATED',
  ROLE_ADMINISTRATION_DYNAMIC_CHECK_DATA_ROLE:
    'ROLE_ADMINISTRATION_DYNAMIC_CHECK_DATA_ROLE',
  ROLE_ADMINISTRATION_DYNAMIC_UNCHECK_DATA_ROLE:
    'ROLE_ADMINISTRATION_DYNAMIC_UNCHECK_DATA_ROLE',
  ROLE_ADMINISTRATION_CHECK_ALL_DATA_ROLE:
    'ROLE_ADMINISTRATION_CHECK_ALL_DATA_ROLE',
  ROLE_ADMINISTRATION_UNCHECK_ALL_DATA_ROLE:
    'ROLE_ADMINISTRATION_UNCHECK_ALL_DATA_ROLE',
  ROLE_ADMINISTRATION_SET_APPLIED_HEADER_SORT:
    'ROLE_ADMINISTRATION_SET_APPLIED_HEADER_SORT',
  ROLE_ADMINISTRATION_RESET_APPLIED_HEADER_SORT:
    'ROLE_ADMINISTRATION_RESET_APPLIED_HEADER_SORT',
};

export default reduxString;
