const reduxString = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_SIGNIN: 'AUTH_SIGNIN',
  GET_TITLE_VERSION: "GET_TITLE_VERSION",
  GET_TITLE_VERSION_FAILED: "GET_TITLE_VERSION_FAILED",
  GET_ENTERPRISE_LOGO: 'GET_ENTERPRISE_LOGO',
  GET_ENTERPRISE_LOGO_FAILED: 'GET_ENTERPRISE_FAILED',
  GET_ENTERPRISE_LOGO_SUCCESS: 'GET_ENTERPRISE_SUCCESS',
  REMOVE_ENTERPRISE_LOGO: 'REMOVE_ENTERPRISE_LOGO',
};
export default reduxString;
