import {colors} from '../constant/color';
export default {
  avatarContainer: {
    width: 152,
    height: 152,
    borderRadius: 100,
    backgroundColor: '#B4B4B4',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  editIcon: {
    position: 'absolute',
    right: 10,
    bottom: -5,
    color: '#707070',
  },
  editIconCard: {
    position: 'relative',
    top: 3,
    color: '#707070',
  },
  accountPlaceholder: {
    flexDirection: 'row',
    width: '70%',
    height: 66,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  nameText: {
    fontSize: 18,
    color: '#707070',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  usernameText: {
    fontSize: 14,
    color: colors.main_color_overlay,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  basicContainer: {
    flexDirection: 'row',
    width: '90%',
    minHeight: 200,
    paddingBottom: 10,
  },
  cardTitleWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    height: 50,
    paddingHorizontal: 15,
  },
  formContainer: {
    width: '100%',
    minHeight: 50,
    alignItems: 'center',
  },
  formGroup: {
    width: '90%',
    paddingVertical: 5,
  },
  label: {
    fontSize: 12,
    color: '#707070',
  },
  textInputContainer: {
    height: 40,
    fontSize: 12,
    // borderRadius: border_radius,
    borderWidth: 1,
    borderColor: '#A8A8A8',
    backgroundColor: 'white',
    borderRadius: 5,
    paddingLeft: 10,
    marginVertical: 10,
    color: '#707070',
  },
  linkText: {
    fontSize: 14,
    color: colors.main_color,
    paddingHorizontal: 15,
  },
  footer: {
    width: '90%',
    alignItems: 'flex-end',
    marginVertical: 15,
  },
  logoutButton: {
    paddingHorizontal: 10,
    fontSize: 18,
    color: '#707070',
  },
  blockButton: {
    width: 100,
    backgroundColor: colors.main_color,
    borderRadius: 5,
    height: 35,
    marginLeft: 15,
    marginVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  passwordRulesContainer: {
    width: '90%',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  buttonGroupContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '80%',
    height: 50,
    marginVertical: 20,
  },
  passwordInputWrapper: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    height: 40,
    borderWidth: 1,
    borderColor: '#A8A8A8',
    backgroundColor: 'white',
    marginVertical: 10,
    color: '#707070',
    justifyContent: 'space-between',
  },
  passwordInput: {
    width: '80%',
    height: '100%',
    paddingLeft: 10,
  },
  buttonShowHide: {
    width: 50,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonGroup: {
    width: 150,
    height: 40,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonBlock: {
    width: '90%',
    height: 40,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'white',
  },
  headerText: {
    textAlign: 'left',
    width: '90%',
    fontSize: 18,
    fontWeight: 'bold',
    paddingVertical: 10,
  },
  documentPickerContainer: {
    height: 40,
    fontSize: 12,
    borderWidth: 1,
    borderColor: '#A8A8A8',
    backgroundColor: 'white',
    borderRadius: 5,
    marginVertical: 10,
    flexDirection: 'row',
  },
  buttonPicker: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '35%',
    height: '100%',
    backgroundColor: colors.main_color,
    borderRadiusTopLeft: 5,
    borderRadiusBottomLeft: 5,
  },
  buttonPickerText: {
    fontSize: 12,
    color: 'white',
  },
  pickerPlaceholderContainer: {
    width: '65%',
    height: '100%',
    paddingHorizontal: 5,
    justifyContent: 'center',
  },
  pickerPlaceholderText: {
    fontSize: 12,
    color: '#707070',
  },
  colorPickerContainer: {
    height: 40,
    flexDirection: 'row',
    marginVertical: 10,
  },
  textInputColorPicker: {
    width: '87%',
    height: 40,
    borderRadius: 5,
    fontSize: 12,
    borderWidth: 1,
    borderColor: '#A8A8A8',
    backgroundColor: 'white',
    paddingHorizontal: 10,
    color: '#707070',
  },
  buttonColorPicker: {
    width: '13%',
    height: 40,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#A8A8A8',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonColorPreview: {
    width: '80%',
    height: '80%',
  },
  modalColorPreview: {
    width: '100%',
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#A8A8A8',
    borderRadius: 5,
  },
  modalColorPreviewText: {
    fontSize: 18,
    color: 'black',
  },
  colorPalleteContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    flexWrap: 'wrap',
  },
  palleteButton: {
    width: 35,
    height: 35,
    borderWidth: 1,
    borderColor: '#A8A8A8',
    borderRadius: 5,
    marginBottom: 10,
    marginHorizontal: 10,
  },
  imagePreviewContainer: {
    width: '100%',
    height: 140,
    justifyContent: 'center',
    // borderRadius: 5,
    shadowColor: '#000',
    paddingHorizontal: 20,
    marginVertical: 10,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 2,
    shadowRadius: 4.65,
    elevation: 8,
  },
  imagePreview: {
    width: 90,
    height: 90,
  },
  buttonFilter: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: 110,
    height: 35,
    borderColor: colors.main_color,
    borderRadius: 20,
    borderWidth: 2,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  filterInput: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '90%',
    height: 50,
    borderColor: colors.main_color,
    borderRadius: 20,
    borderWidth: 2,
    marginHorizontal: 15,
    marginVertical: 5,
  },
  filterTextInput: {
    width: '40%',
    height: 40,
    margin: 8,
    borderBottomWidth: 1,
    padding: 5,
    color: 'black',
    fontSize: 12,
  },
  customTable: {
    width: '95%',
    marginHorizontal: '2.5%',
    borderWidth: 1,
    borderColor: '#A8A8A8',
  },
};
